import { ethers } from 'ethers';
import { performance } from 'perf_hooks';
import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

// ─── CONSTANTS ────────────────────────────────────────────────────────────────

const RPC_URL          = 'http://127.0.0.1:8545';
const DEFAULT_WAVES    = 10;
const DEFAULT_BATCH    = 120;  // 10 wallets × 12 txs per wave
const INTER_WAVE_DELAY = 200;  // ms — RAM fuse between waves
const MONOLITH_GAS     = 150_000n;

// ─── ANVIL DEFAULT KEYS (well-known dev accounts, do NOT use in production) ──

const ANVIL_KEYS = [
  '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
  '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
  '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
  '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6',
  '0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926b',
  '0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba',
  '0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e',
  '0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356',
  '0xdbda1821b80551c9d65939329250132c0148e34efc38ce7bcb6db6ec6b0b6df1',
  '0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6',
];

// ─── ABI FRAGMENTS ────────────────────────────────────────────────────────────

const MONOLITH_ABI = [
  'function deposit(uint256 amount, uint256 clientTimestamp) external',
];

const EXECUTOR_ABI = [
  'function processMicropayment(uint256 channelId, uint256 clientTimestamp, uint256 noncePoW) external payable',
];

// ─── ADDRESS RESOLUTION ───────────────────────────────────────────────────────
// Priority 1: env vars  MONOLITH_ADDR / EXECUTOR_ADDR
// Priority 2: backend/config/deployments.json (generated by Foundry deploy script)

function loadAddresses() {
  if (process.env.MONOLITH_ADDR && process.env.EXECUTOR_ADDR) {
    return {
      monolith: process.env.MONOLITH_ADDR,
      executor: process.env.EXECUTOR_ADDR,
    };
  }

  const __dir    = dirname(fileURLToPath(import.meta.url));
  const jsonPath = resolve(__dir, '../../backend/config/deployments.json');

  if (existsSync(jsonPath)) {
    const d = JSON.parse(readFileSync(jsonPath, 'utf8'));
    return { monolith: d.MonolithDemo, executor: d.VertexExecutor };
  }

  throw new Error(
    "No se encontró backend/config/deployments.json. ¿Ya ejecutaste 'forge script script/Deploy.s.sol' en la terminal de contratos?"
  );
}

// ─── WALLET POOL ──────────────────────────────────────────────────────────────

function buildWalletPool(provider) {
  return ANVIL_KEYS.map(k => new ethers.Wallet(k, provider));
}

// ─── NONCE SNAPSHOT ───────────────────────────────────────────────────────────
// Fetches the *pending* nonce for every wallet in one parallel round-trip.
// Never use a local counter (nonce++) — it causes mempool collisions on Anvil.

async function fetchNonces(wallets) {
  const pending = await Promise.all(wallets.map(w => w.getNonce('pending')));
  return new Map(wallets.map((w, i) => [w.address, pending[i]]));
}

// ─── WAVE: MONOLITH MODE ──────────────────────────────────────────────────────
// All wallets hammer the same flat balances[msg.sender] storage slot.

function buildMonolithWave(wallets, nonceMap, contract, txsPerWallet) {
  const clientTs = Math.floor(Date.now() / 1000);
  return wallets.flatMap((wallet) => {
    const base = nonceMap.get(wallet.address);
    const c    = contract.connect(wallet);
    return Array.from({ length: txsPerWallet }, (_, offset) =>
      c.deposit(ethers.parseEther('0.001'), clientTs, {
        nonce:    base + offset,
        gasLimit: MONOLITH_GAS,
      })
    );
  });
}

// ─── WAVE: VERTEX MODE ────────────────────────────────────────────────────────
// Sends processMicropayment() with powNonce=0 (difficulty=0 in demo deploy).
// channelId rotates 1–10; channel 0 is forbidden (ZeroChannel() guard).

function buildVertexWave(wallets, nonceMap, contract, waveIndex, txsPerWallet) {
  const clientTs = Math.floor(Date.now() / 1000);
  return wallets.flatMap((wallet, wi) => {
    const base = nonceMap.get(wallet.address);
    const c    = contract.connect(wallet);
    return Array.from({ length: txsPerWallet }, (_, offset) => {
      const channelId = BigInt(((wi + waveIndex) % 10) + 1);
      return c.processMicropayment(channelId, clientTs, 0n, {
        nonce: base + offset,
        value: ethers.parseEther('0.001'),
      });
    });
  });
}

// ─── CONSOLE REPORT ───────────────────────────────────────────────────────────

const CLR = {
  red:   '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  cyan:  '\x1b[36m', bold:  '\x1b[1m',  reset:  '\x1b[0m',
};

function reportWave(results, t0, waveIndex, target) {
  const ms   = (performance.now() - t0).toFixed(2);
  const ok   = results.filter(r => r.status === 'fulfilled').length;
  const fail = results.filter(r => r.status === 'rejected').length;
  const tps  = ((results.length / parseFloat(ms)) * 1000).toFixed(0);
  const tag  = target === 'monolith'
    ? `${CLR.red}[MONOLITH]${CLR.reset}`
    : `${CLR.cyan}[VERTEX  ]${CLR.reset}`;

  console.log(
    `${tag} Wave ${String(waveIndex).padStart(2, '0')} │ ` +
    `sent=${CLR.bold}${results.length}${CLR.reset} ` +
    `ok=${CLR.green}${ok}${CLR.reset} ` +
    `rejected=${CLR.yellow}${fail}${CLR.reset} │ ` +
    `${ms}ms │ TPS≈${tps}`
  );
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────

const sleep = ms => new Promise(r => setTimeout(r, ms));

// ─── ORCHESTRATOR ─────────────────────────────────────────────────────────────

async function orchestrate(target, waveCount, batchSize) {
  const provider     = new ethers.JsonRpcProvider(RPC_URL);
  const wallets      = buildWalletPool(provider);
  const addresses    = loadAddresses();
  const txsPerWallet = Math.floor(batchSize / wallets.length);
  const waveBatch    = txsPerWallet * wallets.length;
  const totalTxs     = waveCount * waveBatch;

  const contract = target === 'monolith'
    ? new ethers.Contract(addresses.monolith, MONOLITH_ABI, provider)
    : new ethers.Contract(addresses.executor, EXECUTOR_ABI, provider);

  const targetAddr = target === 'monolith' ? addresses.monolith : addresses.executor;

  console.log(`\n${CLR.bold}╔═══ VERTEX ATTACK ENGINE ═══════════════════════════════════╗${CLR.reset}`);
  console.log(`${CLR.bold}  Target  :${CLR.reset} ${target.toUpperCase()}`);
  console.log(`${CLR.bold}  Address :${CLR.reset} ${targetAddr}`);
  console.log(`${CLR.bold}  Wallets :${CLR.reset} ${wallets.length}   TXs/wallet/wave: ${txsPerWallet}`);
  console.log(`${CLR.bold}  Waves   :${CLR.reset} ${waveCount}   Batch/wave: ${waveBatch}   Total: ${totalTxs}`);
  console.log(`${CLR.bold}╚═════════════════════════════════════════════════════════════╝${CLR.reset}\n`);

  let totalOk   = 0;
  let totalFail = 0;
  const globalT0 = performance.now();

  for (let wave = 1; wave <= waveCount; wave++) {
    const nonceMap = await fetchNonces(wallets);

    const txPromises = target === 'monolith'
      ? buildMonolithWave(wallets, nonceMap, contract, txsPerWallet)
      : buildVertexWave(wallets, nonceMap, contract, wave, txsPerWallet);

    const t0      = performance.now();
    const results = await Promise.allSettled(txPromises);

    reportWave(results, t0, wave, target);
    totalOk   += results.filter(r => r.status === 'fulfilled').length;
    totalFail += results.filter(r => r.status === 'rejected').length;

    if (wave < waveCount) await sleep(INTER_WAVE_DELAY);
  }

  const totalMs = (performance.now() - globalT0).toFixed(0);
  const avgTPS  = totalOk > 0
    ? ((totalOk / parseFloat(totalMs)) * 1000).toFixed(0)
    : '0';

  console.log(`\n${CLR.bold}═══ SUMMARY ════════════════════════════════════════════════${CLR.reset}`);
  console.log(`  Confirmed  : ${CLR.green}${totalOk}${CLR.reset} / ${totalTxs}`);
  console.log(`  Rejected   : ${CLR.yellow}${totalFail}${CLR.reset}`);
  console.log(`  Duration   : ${totalMs}ms`);
  console.log(`  Avg TPS    : ${avgTPS}`);
  console.log(`${CLR.bold}════════════════════════════════════════════════════════════${CLR.reset}\n`);
}

// ─── CLI ENTRY POINT ──────────────────────────────────────────────────────────
// Usage:
//   pnpm monolith
//   pnpm vertex
//   node src/attack.js --target monolith [--waves=N] [--batch=N]
//   node src/attack.js --target vertex   [--waves=N] [--batch=N]

function parseArgs() {
  const args      = process.argv.slice(2);
  const targetArg = args.find(a => a.startsWith('--target=') || a === '--target');
  const wavesArg  = args.find(a => a.startsWith('--waves='));
  const batchArg  = args.find(a => a.startsWith('--batch='));

  let target;
  if (targetArg) {
    target = targetArg.startsWith('--target=')
      ? targetArg.split('=')[1]
      : args[args.indexOf('--target') + 1];
  } else {
    // fallback: first positional arg
    target = args.find(a => !a.startsWith('--'));
  }

  if (!['monolith', 'vertex'].includes(target)) {
    console.error('Usage: node src/attack.js --target <monolith|vertex> [--waves=N] [--batch=N]');
    process.exit(1);
  }

  const waveCount = wavesArg ? parseInt(wavesArg.split('=')[1], 10) : DEFAULT_WAVES;
  const batchSize = batchArg ? parseInt(batchArg.split('=')[1], 10) : DEFAULT_BATCH;

  if (Number.isNaN(waveCount) || waveCount < 1) {
    console.error('--waves must be a positive integer'); process.exit(1);
  }
  if (Number.isNaN(batchSize) || batchSize < ANVIL_KEYS.length) {
    console.error(`--batch must be >= ${ANVIL_KEYS.length} (one tx per wallet minimum)`);
    process.exit(1);
  }

  return { target, waveCount, batchSize };
}

const { target, waveCount, batchSize } = parseArgs();
orchestrate(target, waveCount, batchSize).catch(err => {
  console.error(`${CLR.red}[FATAL]${CLR.reset}`, err.message);
  process.exit(1);
});
